### ISSUE TITLE
Is it possible to generate PLC code according to the skills?

### ISSUE THREAD

**Issue by mf093087** [aljoshakoecher/plc2skill#3]
Is it possible to generate PLC code according to the skills?

**Comment by aljoshakoecher** [comment]
Hey Fan,

I like the idea! But no, this is currently not possible. We went for the opposite approach only. 
By giving PLC developers a library for skill development, we enable them to (more or less) easily develop automation functions as skill implementations. From this skill implementation (= the PLC code), the skill description (in the form of an ontology) can then be created automatically through a mapping application thanks to function blocks defined in the library. These function blocks allow to write mapping rules such as:
`For every function block extending the skill function block, create a skill description` ..

Of course you could also do it the other way: Start by modelling and derive an (empty / template) PLC program from that. But in my head, that immediately raises two questions:
1. How do you create the model? Manually? -> That's very cumbersome and error-prone. You would need an easy way for users to create the skill ontology.
2. What about information coming from the PLC (e.g. OPC UA node information). This can hardly be created top down but instead is better collected when creating the PLC program.

But I really like the idea and would like to discuss with you. What's you motivation in doing it the opposite way?

**Comment by aljoshakoecher** [comment]
Let me know if that makes sense to you or if you have any questions :)

**Comment by mf093087** [comment]
> 

Hi Aljosha,

Many thanks for your reply! We want to find out how to generate PLC code according to the skills, because we want to achieve quick response and PLC code generation based on the customer request. For example, the customer want a product, the operations needed to produce the product are clear, it would be nice to know how to generate the PLC code automatically based on the needed operations. 

Yours,
Fan

**Comment by mf093087** [comment]
What I am thinking now is to build a mapper between the skill and the PLCopen format code.

**Comment by aljoshakoecher** [comment]
Yeah, that seems to be well-suited for cases, in which you want to give PLC programmers a fixed guideline (i.e. a skill model) which they should implement. For such cases, you could really apply the opposite approach, generate PLCopen XML from the skill model and import this PLCopen XML into a PLC programming IDE to then implement it.

This is now quite a funny coincidence, but a general mapping from an ontology / knowledge graph to XML is something I am working on with a colleague, maybe you want to checkout this repository: https://github.com/hsu-aut/olif
The approach is presented in an initial work-in-progress paper: https://arxiv.org/pdf/2207.11205.pdf

The mapping tool is currently in devlopment and not easily usable, but there will be an initial version next week. I will keep you updated - maybe you can use it for your mapping?

**Comment by mf093087** [comment]
Thanks a lot! Please keep me updated. :)

**Comment by aljoshakoecher** [comment]
I just released a first version of this mapping application, you can find the release here: https://github.com/hsu-aut/olif/releases/tag/v0.0.1. Just download the jar and use it as described in the readme. I hope documentation is sufficient to get started.
Please note that this is a very early version and we are (more or less) constantly working on it to improve it and prepare a larger publication. While I am fairly happy with Olif so far, there is a good chance that you will encounter bugs. In such cases, it would be super helpful if you could raise an issue in the Olif repository. For now I am closing this discussion, but feel free to open another issue or send an email for future questions / problems.
